apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\v.harlamov\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: authorization-server
  name: authorization_server
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: authorization-server
status:
  loadBalancer: {}
