apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\v.harlamov\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\v.harlamov\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/ecommercejava-default: "true"
        io.kompose.service: client
    spec:
      containers:
        - image: keyist-client1:latest
          name: client
          ports:
            - containerPort: 80
              hostPort: 4200
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
