apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\v.harlamov\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 80
  selector:
    io.kompose.service: client
status:
  loadBalancer: {}
